#!/bin/bash

# With no arguments, this script must install from an unpacked tgz.

PRE=$1;
if [[ -z $PRE ]]; then
	PRE=/usr;
fi

BIN=$PRE/bin;
DOC=$PRE/share/doc/code_crusader;
LIB=$PRE/lib/jxcb;
APP=$PRE/share/applications;
ICON=$PRE/share/pixmaps;

mkdir -p $BIN;
install -m755 jcc                    $BIN;
install -m755 macros/xml-auto-close  $BIN;
install -m755 macros/html-auto-close $BIN;

ln -sf jcc $BIN/code_crusader;

mkdir -p $LIB;
cp -R project_templates $LIB;
cp -R scripts           $LIB;

mkdir -p $DOC;
cp README.md menu_strings $DOC;
cp -R macros              $DOC;
cp -R CPM_rules           $DOC;

if [[ -d desktop ]]; then
	mkdir -p $APP $ICON;
	cp desktop/code_crusader.desktop $APP/;
	cp desktop/code_crusader.xpm     $ICON/;
fi
