#!/bin/bash

PRE=$1;
if [[ -z $PRE ]]; then
	PRE=/usr/local;
fi

BIN=$PRE/bin;
DOC=$PRE/share/doc/code-crusader;
LIB=$PRE/share/jxcb;
APP=$PRE/share/applications;
ICON=$PRE/share/pixmaps;

rm -f  $BIN/jcc;
rm -f  $BIN/code-crusader;
rm -f  $BIN/xml-auto-close;
rm -f  $BIN/html-auto-close;
rm -f  $BIN/java-import;
rm -rf $LIB;
rm -rf $DOC;
rm -f  `find $APP -name 'code_crusader*.desktop'`;
rm -f  `find $ICON -name 'code_crusader*.png'`;
