#!/bin/bash

# With no arguments, this script must install from an unpacked tgz.

PRE=$1;

BIN=$PRE/usr/bin;
DOC=$PRE/usr/share/doc/code-mill;
APP=$PRE/usr/share/applications;

mkdir -p $BIN;
install -m755 code-mill $BIN;

mkdir -p $DOC;
cp README.md COPYING menu_strings $DOC;

if [[ -d desktop ]]; then
	mkdir -p $APP;
	cp desktop/code_mill.desktop $APP/;
fi
