#!/bin/bash

# With no arguments, this script must install from an unpacked tgz.

PRE=$1;
if [[ -z $PRE ]]; then
	PRE=/usr/local;
fi

BIN=$PRE/bin;
DOC=$PRE/share/doc/code-mill;
APP=$PRE/share/applications;

mkdir -p $BIN;
install -m755 code-mill $BIN;

mkdir -p $DOC;
cp README.md COPYING menu_strings $DOC;
