#!/bin/bash

# With no arguments, this script must install from an unpacked tgz.

PRE=$1;
if [[ -z $PRE ]]; then
	PRE=/usr;
fi

BIN=$PRE/bin;
DOC=$PRE/share/doc/code_mill;
APP=$PRE/share/applications;
ICON=$PRE/share/pixmaps;

mkdir -p $BIN;
install -m755 code_mill $BIN;

mkdir -p $DOC;
cp README.md COPYING menu_strings $DOC;

if [[ -d desktop ]]; then
	mkdir -p $APP $ICON;
	cp desktop/code_mill.desktop $APP/;
	cp desktop/code_mill.xpm     $ICON/;
fi
