#!/bin/bash

PRE=$1;
if [[ -z $PRE ]]; then
	if [[ `uname -o` == Darwin ]]; then
		PRE=`brew --prefix`;
	else
		PRE=/usr/local;
	fi;
fi

BIN=$PRE/bin;
DOC=$PRE/share/doc/code-mill;

rm -f  $BIN/code-mill;
rm -rf $DOC;
