#!/bin/bash

PRE=$1;
if [[ -z $PRE ]]; then
	PRE=/usr/local;
fi

BIN=$PRE/bin;
DOC=$PRE/share/doc/code-mill;
APP=$PRE/share/applications;

rm -f  $BIN/code-mill;
rm -rf $DOC;
rm -f  `find $APP -name 'code_mill*.desktop'`;
