// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_BreakpointsDir_Actions
#define _H_BreakpointsDir_Actions

static const JUtf8Byte* kActionsMenuStr =
"* %i EnableAllBreakpoints::BreakpointsDir"
"|* %i DisableAllBreakpoints::BreakpointsDir %l"
"|* %i ClearAllBreakpoints::BreakpointsDir"
;

enum {
	kEnableAllBreakpointsCmd=1,
	kDisableAllBreakpointsCmd,
	kRemoveAllBreakpointsCmd,
};


static void ConfigureActionsMenu(JXTextMenu* menu, const int offset = 0) {
	if (offset == 0 && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts(JString("#a", JString::kNoCopy));
	}
};

#endif
