// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_CommandDirector_File
#define _H_CommandDirector_File

static const JUtf8Byte* kFileMenuStr =
"* %i OpenSourceFile::CommandDirector %l"
"|* %i LoadConfig::CommandDirector"
"|* %i SaveConfig::CommandDirector %l"
"|* %i SaveHistory::CommandDirector"
"|* %i SaveHistoryAs::CommandDirector %l"
"|* %i PageSetup::JX"
"|* %i Print::JX %l"
"|* %i CloseWindow::JX"
"|* %i Quit::JX"
;

#include "CommandDirector-File-enum.h"

#ifndef _H_jx_af_image_jx_jx_file_open
#define _H_jx_af_image_jx_jx_file_open
#include <jx-af/image/jx/jx_file_open.xpm>
#endif
#ifndef _H_jx_af_image_jx_jx_file_print
#define _H_jx_af_image_jx_jx_file_print
#include <jx-af/image/jx/jx_file_print.xpm>
#endif

static void ConfigureFileMenu(JXTextMenu* menu, const int offset = 0) {
	if (offset == 0 && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts("#f");
	}
	menu->SetItemImage(kOpenCmd + offset, jx_file_open);
	menu->SetItemImage(kPrintCmd + offset, jx_file_print);
};

#endif
