// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_CommandDirector_Preferences
#define _H_CommandDirector_Preferences

static const JUtf8Byte* kPreferencesMenuStr =
"* %i __Preferences::CommandDirector"
"|* %i __ToolbarButtons::CommandDirector"
"|* %i __CustomCommands::CommandDirector"
"|* %i __MacWinXEmulation::CommandDirector %l"
"|* %r %i __gdb::CommandDirector"
"|* %r %i __lldb::CommandDirector"
"|* %r %i __Java::CommandDirector"
"|* %r %i __Xdebug::CommandDirector"
;

#include "CommandDirector-Preferences-enum.h"


static void ConfigurePreferencesMenu(JXTextMenu* menu, const int offset = 0) {
	if (offset == 0 && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts("#p");
	}
};

#endif
