// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_CommandDirector_Preferences_enum
#define _H_CommandDirector_Preferences_enum

enum {
	kEditPrefsCmd=1,
	kEditToolBarCmd,
	kEditCmdsCmd,
	kEditMacWinPrefsCmd,
	kUseGDBCmd,
	kUseLLDBCmd,
	kUseJavaCmd,
	kUseXdebugCmd,
};

#endif
