// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_FileListDir_Actions_enum
#define _H_FileListDir_Actions_enum

enum {
	kShowFilterCmd=1,
	kShowRegexCmd,
};

#endif
