// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_Generic_Debug_enum
#define _H_Generic_Debug_enum

enum {
	kSelectBinCmd=1,
	kReloadBinCmd,
	kSelectCoreCmd,
	kSelectProcessCmd,
	kSetArgsCmd,
	kRestartDebuggerCmd,
	kDisplayVarCmd,
	kDisplay1DArrayCmd,
	kPlot1DArrayCmd,
	kDisplay2DArrayCmd,
	kWatchVarCmd,
	kWatchLocCmd,
	kExamineMemCmd,
	kDisassembleMemCmd,
	kDisassembleFnCmd,
	kRunCmd,
	kStopCmd,
	kKillCmd,
	kNextCmd,
	kStepCmd,
	kFinishCmd,
	kContCmd,
	kNextAsmCmd,
	kStepAsmCmd,
	kPrevCmd,
	kReverseStepCmd,
	kReverseFinishCmd,
	kReverseContCmd,
	kRemoveAllBreakpointsCmd,
};

#endif
