// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_LocalVarsDir_Actions
#define _H_LocalVarsDir_Actions

static const JUtf8Byte* kActionsMenuStr =
"* %i Display1DArray::LocalVarsDir"
"|* %i Plot1DArray::LocalVarsDir"
"|* %i Display2DArray::LocalVarsDir %l"
"|* %i WatchVarValue::LocalVarsDir"
"|* %i WatchVarLocation::LocalVarsDir %l"
"|* %i ExamineMemory::LocalVarsDir"
"|* %i DisasmMemory::LocalVarsDir"
;

#include "LocalVarsDir-Actions-enum.h"


static void ConfigureActionsMenu(JXTextMenu* menu, const int offset = 0) {
	if (offset == 0 && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts("#a");
	}
};

#endif
