// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_LocalVarsDir_Actions
#define _H_LocalVarsDir_Actions

static const JUtf8Byte* kActionsMenuStr =
"* %i DisplayAsCStringAction::LocalVarsDir %l"
"|* %i Display1DArray::LocalVarsDir"
"|* %i Plot1DArray::LocalVarsDir"
"|* %i Display2DArray::LocalVarsDir %l"
"|* %i WatchVarValue::LocalVarsDir"
"|* %i WatchVarLocation::LocalVarsDir %l"
"|* %i ExamineMemory::LocalVarsDir"
"|* %i DisasmMemory::LocalVarsDir"
;

enum {
	kDisplayAsCStringCmd=1,
	kDisplay1DArrayCmd,
	kPlot1DArrayCmd,
	kDisplay2DArrayCmd,
	kWatchVarCmd,
	kWatchLocCmd,
	kExamineMemCmd,
	kDisassembleMemCmd,
};

#ifndef _H_medic_show_1d_array
#define _H_medic_show_1d_array
#include "medic_show_1d_array.xpm"
#endif
#ifndef _H_medic_show_2d_plot
#define _H_medic_show_2d_plot
#include "medic_show_2d_plot.xpm"
#endif
#ifndef _H_medic_show_2d_array
#define _H_medic_show_2d_array
#include "medic_show_2d_array.xpm"
#endif
#ifndef _H_medic_show_memory
#define _H_medic_show_memory
#include "medic_show_memory.xpm"
#endif

static void ConfigureActionsMenu(JXTextMenu* menu, const int offset = 0) {
	if (offset == 0 && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts(JString("#a", JString::kNoCopy));
	}
	menu->SetItemImage(kDisplay1DArrayCmd + offset, medic_show_1d_array);
	menu->SetItemImage(kPlot1DArrayCmd + offset, medic_show_2d_plot);
	menu->SetItemImage(kDisplay2DArrayCmd + offset, medic_show_2d_array);
	menu->SetItemImage(kExamineMemCmd + offset, medic_show_memory);
};

#endif
