// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_MemoryDir_DisplayType_enum
#define _H_MemoryDir_DisplayType_enum

enum {
	____HexBytes=1,
	____HexShort2Bytes,
	____HexWord4Bytes,
	____HexLong8Bytes,
	____CharactersISO88591,
	____AssemblyCode,
};

#endif
