// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_MemoryDir_Actions_enum
#define _H_MemoryDir_Actions_enum

enum {
	kSavePrefsCmd=1,
};

#endif
