// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_Plot2DDir_File_enum
#define _H_Plot2DDir_File_enum

enum {
	kOpenCmd=1,
	kPSPageSetupCmd,
	kPrintPSCmd,
	kPrintEPSCmd,
	kCloseWindowCmd,
	kQuitCmd,
};

#endif
