// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_Plot2DDir_File
#define _H_Plot2DDir_File

static const JUtf8Byte* kFileMenuStr =
"* %i OpenSourceFile::Plot2DDir %l"
"|* %i PageSetup::JX"
"|* %i Print::JX"
"|* %i Print::JX %l"
"|* %i CloseWindow::JX"
"|* %i Quit::JX"
;

enum {
	kOpenCmd=1,
	kPSPageSetupCmd,
	kPrintPSCmd,
	kPrintEPSCmd,
	kCloseWindowCmd,
	kQuitCmd,
};

#ifndef _H_jx_af_image_jx_jx_file_open
#define _H_jx_af_image_jx_jx_file_open
#include <jx-af/image/jx/jx_file_open.xpm>
#endif
#ifndef _H_jx_af_image_jx_jx_file_print
#define _H_jx_af_image_jx_jx_file_print
#include <jx-af/image/jx/jx_file_print.xpm>
#endif

static void ConfigureFileMenu(JXTextMenu* menu, const int offset = 0) {
	if (offset == 0 && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts(JString("#f", JString::kNoCopy));
	}
	menu->SetItemImage(kOpenCmd + offset, jx_file_open);
	menu->SetItemImage(kPrintPSCmd + offset, jx_file_print);
};

#endif
