// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_SourceDirector_Preferences_enum
#define _H_SourceDirector_Preferences_enum

enum {
	kEditPrefsCmd=1,
	kEditToolBarCmd,
	kEditCmdsCmd,
	kEditMacWinPrefsCmd,
	kWindowSizeCmd,
};

#endif
