// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_SourceText_Search_enum
#define _H_SourceText_Search_enum

enum {
	kBalanceCmd=1,
	kGoToLineCmd,
	kGoToCurrentLineCmd,
};

#endif
