// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_VarTreeWidget_Edit
#define _H_VarTreeWidget_Edit

static const JUtf8Byte* kEditMenuStr =
"* %i CopyFullVarName::VarTreeWidget"
"|* %i CopyVarValue::VarTreeWidget"
;

enum {
	__CopyFullVarName=1,
	__CopyVarValue,
};


static void ConfigureEditMenu(JXTextMenu* menu, const int offset = 0) {
};

#endif
