// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_VarTreeWidget_Base
#define _H_VarTreeWidget_Base

static const JUtf8Byte* kBaseMenuStr =
"* %r %i __Default::VarTreeWidget %l"
"|* %r %i __10::VarTreeWidget %l"
"|* %r %i __2::VarTreeWidget"
"|* %r %i __8::VarTreeWidget"
"|* %r %i __16::VarTreeWidget %l"
"|* %r %i __ASCII::VarTreeWidget"
;

enum {
	kDefaultBase=1,
	kBase10,
	kBase2,
	kBase8,
	kBase16,
	kBaseASCII,
};


static void ConfigureBaseMenu(JXTextMenu* menu, const int offset = 0) {
	if (offset == 0 && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts(JString("#b", JString::kNoCopy));
	}
};

#endif
