// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_VarTreeWidget_Base_enum
#define _H_VarTreeWidget_Base_enum

enum {
	kDefaultBase=1,
	kBase10,
	kBase2,
	kBase8,
	kBase16,
	kBaseASCII,
};

#endif
