// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_VarTreeDir_Actions_enum
#define _H_VarTreeDir_Actions_enum

enum {
	kAddVarCmd=1,
	kDelVarCmd,
	kDisplayAsCStringCmd,
	kDisplay1DArrayCmd,
	kPlot1DArrayCmd,
	kDisplay2DArrayCmd,
	kWatchVarCmd,
	kWatchLocCmd,
	kExamineMemCmd,
	kDisassembleMemCmd,
};

#endif
