// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_VarTreeWidget_Edit_enum
#define _H_VarTreeWidget_Edit_enum

enum {
	__CopyFullVarName=1,
	__CopyVarValue,
};

#endif
