// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_CommandMenu_AddToProject
#define _H_CommandMenu_AddToProject

static const JUtf8Byte* kAddToProjectMenuStr =
"* %i AddToProjAbsolute::CommandMenu"
"|* %i AddToProjProjRelative::CommandMenu"
"|* %i AddToProjHomeRelative::CommandMenu"
;

enum {
	kAddToProjAbsoluteCmd=1,
	kAddToProjProjRelativeCmd,
	kAddToProjHomeRelativeCmd,
};


static void ConfigureAddToProjectMenu(JXTextMenu* menu, const int offset = 0) {
};

#endif
