// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_CommandMenu_Tasks_enum
#define _H_CommandMenu_Tasks_enum

enum {
	kRunCmd=1,
	kEditCmd,
	kAddToProjIndex,
	kManageProjIndex,
};

#endif
