// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_CommandTable_Options_enum
#define _H_CommandTable_Options_enum

enum {
	kIsMakeCmd=1,
	kIsCVSCmd,
	kSaveAllCmd,
	kOneAtATimeCmd,
	kUseWindowCmd,
	kRaisedWhenStartCmd,
	kBeepWhenFinishedCmd,
	kShowSeparatorCmd,
};

#endif
