// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_CommandTable_Options
#define _H_CommandTable_Options

static const JUtf8Byte* kOptionsMenuStr =
"* %b %i __ThisTaskInvokesMakeAntEtc::CommandTable"
"|* %b %i __ThisTaskInvokesVersionControl::CommandTable %l"
"|* %b %i __SaveAllFilesBeforePerforming::CommandTable"
"|* %b %i __PerformOnOneFileAtATime::CommandTable %l"
"|* %b %i __DisplayOutputInWindow::CommandTable"
"|* %b %i __RaiseWindowBeforePerforming::CommandTable"
"|* %b %i __BeepWhenTaskIsFinished::CommandTable %l"
"|* %b %i __DisplaySeparatorAfterThisItemInMenu::CommandTable"
;

#include "CommandTable-Options-enum.h"


static void ConfigureOptionsMenu(JXTextMenu* menu, const int offset = 0) {
};

#endif
