// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_CommandMenu_ManageProject_enum
#define _H_CommandMenu_ManageProject_enum

enum {
	kUpdateSymbolDBCmd=1,
	kShowSymbolBrowserCmd,
	kShowCTreeCmd,
	kShowDTreeCmd,
	kShowGoTreeCmd,
	kShowJavaTreeCmd,
	kShowPHPTreeCmd,
	kShowFileListCmd,
};

#endif
