// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_CommandMenu_ManageProject
#define _H_CommandMenu_ManageProject

static const JUtf8Byte* kManageProjectMenuStr =
"* %i UpdateClassTree::CommandMenu %l"
"|* %i ShowSymbolBrowser::CommandMenu"
"|* %i ShowCPPClassTree::CommandMenu"
"|* %i ShowDClassTree::CommandMenu"
"|* %i ShowGoClassTree::CommandMenu"
"|* %i ShowJavaClassTree::CommandMenu"
"|* %i ShowPHPClassTree::CommandMenu"
"|* %i ShowFileList::CommandMenu"
;

enum {
	kUpdateSymbolDBCmd=1,
	kShowSymbolBrowserCmd,
	kShowCTreeCmd,
	kShowDTreeCmd,
	kShowGoTreeCmd,
	kShowJavaTreeCmd,
	kShowPHPTreeCmd,
	kShowFileListCmd,
};

#ifndef _H_jcc_show_symbol_list
#define _H_jcc_show_symbol_list
#include "jcc_show_symbol_list.xpm"
#endif
#ifndef _H_jcc_show_c_tree
#define _H_jcc_show_c_tree
#include "jcc_show_c_tree.xpm"
#endif
#ifndef _H_jcc_show_d_tree
#define _H_jcc_show_d_tree
#include "jcc_show_d_tree.xpm"
#endif
#ifndef _H_jcc_show_go_tree
#define _H_jcc_show_go_tree
#include "jcc_show_go_tree.xpm"
#endif
#ifndef _H_jcc_show_java_tree
#define _H_jcc_show_java_tree
#include "jcc_show_java_tree.xpm"
#endif
#ifndef _H_jcc_show_php_tree
#define _H_jcc_show_php_tree
#include "jcc_show_php_tree.xpm"
#endif
#ifndef _H_jcc_show_file_list
#define _H_jcc_show_file_list
#include "jcc_show_file_list.xpm"
#endif

static void ConfigureManageProjectMenu(JXTextMenu* menu, const int offset = 0) {
	menu->SetItemImage(kShowSymbolBrowserCmd + offset, jcc_show_symbol_list);
	menu->SetItemImage(kShowCTreeCmd + offset, jcc_show_c_tree);
	menu->SetItemImage(kShowDTreeCmd + offset, jcc_show_d_tree);
	menu->SetItemImage(kShowGoTreeCmd + offset, jcc_show_go_tree);
	menu->SetItemImage(kShowJavaTreeCmd + offset, jcc_show_java_tree);
	menu->SetItemImage(kShowPHPTreeCmd + offset, jcc_show_php_tree);
	menu->SetItemImage(kShowFileListCmd + offset, jcc_show_file_list);
};

#endif
