// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_CompileDocument_Errors_enum
#define _H_CompileDocument_Errors_enum

enum {
	kFirstErrorCmd=1,
	kPrevErrorCmd,
	kNextErrorCmd,
	kOpenFileCmd,
};

#endif
