// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_CTreeDirector_Tree_enum
#define _H_CTreeDirector_Tree_enum

enum {
	kEditCPPMacrosCmd=1,
	kEditSearchPathsCmd,
	kUpdateCurrentCmd,
	kForceMinMILinksCmd,
	kTreeOpenSourceCmd,
	kTreeOpenHeaderCmd,
	kTreeOpenFnListCmd,
	kCreateDerivedClassCmd,
	kTreeCollapseCmd,
	kTreeExpandCmd,
	kTreeExpandAllCmd,
	kTreeSelParentsCmd,
	kTreeSelDescendantsCmd,
	kCopySelNamesCmd,
	kFindFnCmd,
};

#endif
