// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_DiffFileDialog_SVNRev1_enum
#define _H_DiffFileDialog_SVNRev1_enum

enum {
	__Current_SVN1=1,
	__Previous_SVN1,
	__Revision_SVN1,
	__DateYMD_SVN1,
	__Trunk_SVN1,
	__Branch_SVN1,
	__Tag_SVN1,
};

#endif
