// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_DiffFileDialog_GitRev2_enum
#define _H_DiffFileDialog_GitRev2_enum

enum {
	__Edited_Git2=1,
	__Current_Git2,
	__Commit_Git2,
	__Date_Git2,
	__Branch_Git2,
};

#endif
