// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_DiffFileDialog_GitRev1
#define _H_DiffFileDialog_GitRev1

static const JUtf8Byte* kGitRev1MenuStr =
"* %r %i __Current::DiffFileDialog"
"|* %r %i __Previous::DiffFileDialog"
"|* %r %i __Commit::DiffFileDialog"
"|* %r %i __Date::DiffFileDialog"
"|* %r %i __Branch::DiffFileDialog"
"|* %r %i __CommonAncestorOf::DiffFileDialog"
;

#include "DiffFileDialog-GitRev1-enum.h"


static void ConfigureGitRev1Menu(JXTextMenu* menu, const int offset = 0) {
};

#endif
