// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_DiffFileDialog_GitRev1
#define _H_DiffFileDialog_GitRev1

static const JUtf8Byte* kGitRev1MenuStr =
"* %r %i __Current::DiffFileDialog"
"|* %r %i __Previous::DiffFileDialog"
"|* %r %i __Commit::DiffFileDialog"
"|* %r %i __Date::DiffFileDialog"
"|* %r %i __Branch::DiffFileDialog"
"|* %r %i __CommonAncestorOf::DiffFileDialog"
;

enum {
	__Current_Git1=1,
	__Previous_Git1,
	__Commit_Git1,
	__Date_Git1,
	__Branch_Git1,
	__CommonAncestorOf_Git1,
};


static void ConfigureGitRev1Menu(JXTextMenu* menu, const int offset = 0) {
};

#endif
