// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_DiffFileDialog_SVNRev2
#define _H_DiffFileDialog_SVNRev2

static const JUtf8Byte* kSVNRev2MenuStr =
"* %r %i __Edited::DiffFileDialog"
"|* %r %i __Current::DiffFileDialog"
"|* %r %i __Revision::DiffFileDialog"
"|* %r %i __DateYMD::DiffFileDialog %l"
"|* %r %i __Trunk::DiffFileDialog"
"|* %r %i __Branch::DiffFileDialog"
"|* %r %i __Tag::DiffFileDialog"
;

#include "DiffFileDialog-SVNRev2-enum.h"


static void ConfigureSVNRev2Menu(JXTextMenu* menu, const int offset = 0) {
};

#endif
