// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_DiffFileDialog_CVSRev1
#define _H_DiffFileDialog_CVSRev1

static const JUtf8Byte* kCVSRev1MenuStr =
"* %r %i __Current::DiffFileDialog"
"|* %r %i __Previous::DiffFileDialog"
"|* %r %i __Tag::DiffFileDialog"
"|* %r %i __Date::DiffFileDialog"
;

#include "DiffFileDialog-CVSRev1-enum.h"


static void ConfigureCVSRev1Menu(JXTextMenu* menu, const int offset = 0) {
};

#endif
