// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_DiffFileDialog_GitRev2
#define _H_DiffFileDialog_GitRev2

static const JUtf8Byte* kGitRev2MenuStr =
"* %r %i __Edited::DiffFileDialog"
"|* %r %i __Current::DiffFileDialog"
"|* %r %i __Commit::DiffFileDialog"
"|* %r %i __Date::DiffFileDialog"
"|* %r %i __Branch::DiffFileDialog"
;

#include "DiffFileDialog-GitRev2-enum.h"


static void ConfigureGitRev2Menu(JXTextMenu* menu, const int offset = 0) {
};

#endif
