// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_DiffFileDialog_CVSRev2
#define _H_DiffFileDialog_CVSRev2

static const JUtf8Byte* kCVSRev2MenuStr =
"* %r %i __Edited::DiffFileDialog"
"|* %r %i __Current::DiffFileDialog"
"|* %r %i __Tag::DiffFileDialog"
"|* %r %i __Date::DiffFileDialog"
;

#include "DiffFileDialog-CVSRev2-enum.h"


static void ConfigureCVSRev2Menu(JXTextMenu* menu, const int offset = 0) {
};

#endif
