// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_DiffFileDialog_CVSRev2_enum
#define _H_DiffFileDialog_CVSRev2_enum

enum {
	__Edited_CVS2=1,
	__Current_CVS2,
	__Tag_CVS2,
	__Date_CVS2,
};

#endif
