// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_DiffFileDialog_SVNRev1
#define _H_DiffFileDialog_SVNRev1

static const JUtf8Byte* kSVNRev1MenuStr =
"* %r %i __Current::DiffFileDialog"
"|* %r %i __Previous::DiffFileDialog"
"|* %r %i __Revision::DiffFileDialog"
"|* %r %i __DateYMD::DiffFileDialog %l"
"|* %r %i __Trunk::DiffFileDialog"
"|* %r %i __Branch::DiffFileDialog"
"|* %r %i __Tag::DiffFileDialog"
;

#include "DiffFileDialog-SVNRev1-enum.h"


static void ConfigureSVNRev1Menu(JXTextMenu* menu, const int offset = 0) {
};

#endif
