// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_DiffFileDialog_SVNRev2_enum
#define _H_DiffFileDialog_SVNRev2_enum

enum {
	__Edited_SVN2=1,
	__Current_SVN2,
	__Revision_SVN2,
	__DateYMD_SVN2,
	__Trunk_SVN2,
	__Branch_SVN2,
	__Tag_SVN2,
};

#endif
