// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_DiffFileDialog_CVSRev1_enum
#define _H_DiffFileDialog_CVSRev1_enum

enum {
	__Current_CVS1=1,
	__Previous_CVS1,
	__Tag_CVS1,
	__Date_CVS1,
};

#endif
