// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_DiffFileDialog_GitRev1_enum
#define _H_DiffFileDialog_GitRev1_enum

enum {
	__Current_Git1=1,
	__Previous_Git1,
	__Commit_Git1,
	__Date_Git1,
	__Branch_Git1,
	__CommonAncestorOf_Git1,
};

#endif
