// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_DiffDocument_Differences_enum
#define _H_DiffDocument_Differences_enum

enum {
	kFirstDiffCmd=1,
	kPrevDiffCmd,
	kNextDiffCmd,
};

#endif
