// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_EditTextPrefsDialog_Emulator
#define _H_EditTextPrefsDialog_Emulator

static const JUtf8Byte* kEmulatorMenuStr =
"* %r %i __None::EditTextPrefsDialog"
"|* %r %i __vi::EditTextPrefsDialog"
;

enum {
	kNoEmulatorCmd=1,
	kVIEmulatorCmd,
};


static void ConfigureEmulatorMenu(JXTextMenu* menu, const int offset = 0) {
	if (offset == 0 && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts(JString("#e", JString::kNoCopy));
	}
};

#endif
