// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_FileListDirector_Preferences
#define _H_FileListDirector_Preferences

static const JUtf8Byte* kPreferencesMenuStr =
"* %i __ToolbarButtons::FileListDirectorx"
"|* %i __FileTypes::FileListDirectorx"
"|* %i __ExternalEditors::FileListDirectorx"
"|* %i __FileManagerWebBrowser::FileListDirectorx"
"|* %i __Miscellaneous::FileListDirectorx %l"
"|* %i __SaveWindowSizeAsDefault::FileListDirectorx"
;

enum {
	kToolBarPrefsCmd=1,
	kEditFileTypesCmd,
	kChooseExtEditorsCmd,
	kShowLocationPrefsCmd,
	kMiscPrefsCmd,
	kSaveWindSizeCmd,
};


static void ConfigurePreferencesMenu(JXTextMenu* menu, const int offset = 0) {
	if (offset == 0 && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts(JString("#p", JString::kNoCopy));
	}
};

#endif
