// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_FileListDirector_List_enum
#define _H_FileListDirector_List_enum

enum {
	kOpenSelectionCmd=1,
	kShowLocationCmd,
	kUpdateCmd,
	kUseWildcardCmd,
	kUseRegexCmd,
};

#endif
