// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_FileTypeTable_Type
#define _H_FileTypeTable_Type

static const JUtf8Byte* kTypeMenuStr =
"* %r %i __AdobeFlash::FileTypeTable"
"|* %r %i __Ant::FileTypeTable"
"|* %r %i __Assembly::FileTypeTable"
"|* %r %i __ASP::FileTypeTable"
"|* %r %i __AWK::FileTypeTable"
"|* %r %i __Basic::FileTypeTable"
"|* %r %i __Beta::FileTypeTable"
"|* %r %i __Bison::FileTypeTable"
"|* %r %i __BourneShellSh::FileTypeTable"
"|* %r %i __CShellCsh::FileTypeTable"
"|* %r %i __CCSource::FileTypeTable"
"|* %r %i __CCHeader::FileTypeTable"
"|* %r %i __C::FileTypeTable"
"|* %r %i __Cobol::FileTypeTable"
"|* %r %i __D::FileTypeTable"
"|* %r %i __Eiffel::FileTypeTable"
"|* %r %i __Erlang::FileTypeTable"
"|* %r %i __FORTRAN::FileTypeTable"
"|* %r %i __Go::FileTypeTable"
"|* %r %i __HTML::FileTypeTable"
"|* %r %i __INI::FileTypeTable"
"|* %r %i __JavaArchive::FileTypeTable"
"|* %r %i __JavaProperties::FileTypeTable"
"|* %r %i __JavaSource::FileTypeTable"
"|* %r %i __JavaScript::FileTypeTable"
"|* %r %i __JSP::FileTypeTable"
"|* %r %i __Lex::FileTypeTable"
"|* %r %i __Lisp::FileTypeTable"
"|* %r %i __Lua::FileTypeTable"
"|* %r %i __Make::FileTypeTable"
"|* %r %i __Matlab::FileTypeTable"
"|* %r %i __Modula2Module::FileTypeTable"
"|* %r %i __Modula2Interface::FileTypeTable"
"|* %r %i __Modula3Module::FileTypeTable"
"|* %r %i __Modula3Interface::FileTypeTable"
"|* %r %i __Pascal::FileTypeTable"
"|* %r %i __Perl::FileTypeTable"
"|* %r %i __PHP::FileTypeTable"
"|* %r %i __Python::FileTypeTable"
"|* %r %i __Ratfor::FileTypeTable"
"|* %r %i __REXX::FileTypeTable"
"|* %r %i __Ruby::FileTypeTable"
"|* %r %i __Scheme::FileTypeTable"
"|* %r %i __SLang::FileTypeTable"
"|* %r %i __SML::FileTypeTable"
"|* %r %i __SQL::FileTypeTable"
"|* %r %i __TCL::FileTypeTable"
"|* %r %i __VeraSource::FileTypeTable"
"|* %r %i __VeraHeader::FileTypeTable"
"|* %r %i __Verilog::FileTypeTable"
"|* %r %i __Vim::FileTypeTable"
"|* %r %i __XML::FileTypeTable"
"|* %r %i __OtherSource::FileTypeTable"
"|* %r %i __StaticLibrary::FileTypeTable"
"|* %r %i __SharedLibrary::FileTypeTable"
"|* %r %i __Documentation::FileTypeTable"
"|* %r %i __OtherText::FileTypeTable"
"|* %r %i __Binary::FileTypeTable"
"|* %r %i __External::FileTypeTable"
;

#include "FileTypeTable-Type-enum.h"


static void ConfigureTypeMenu(JXTextMenu* menu, const int offset = 0) {
};

#endif
