// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_FileListDirector_List
#define _H_FileListDirector_List

static const JUtf8Byte* kListMenuStr =
"* %i OpenSelectedFiles::FileListDirector"
"|* %i OpenSelectedFileLocations::FileListDirector"
"|* %i UpdateClassTree::FileListDirector %l"
"|* %b %i UseWildcardFilter::FileListDirector"
"|* %b %i UseRegexFilter::FileListDirector"
;

enum {
	kOpenSelectionCmd=1,
	kShowLocationCmd,
	kUpdateCmd,
	kUseWildcardCmd,
	kUseRegexCmd,
};

#ifndef _H_jx_af_image_jx_jx_filter_wildcard
#define _H_jx_af_image_jx_jx_filter_wildcard
#include <jx-af/image/jx/jx_filter_wildcard.xpm>
#endif
#ifndef _H_jx_af_image_jx_jx_filter_regex
#define _H_jx_af_image_jx_jx_filter_regex
#include <jx-af/image/jx/jx_filter_regex.xpm>
#endif

static void ConfigureListMenu(JXTextMenu* menu, const int offset = 0) {
	if (offset == 0 && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts(JString("#l", JString::kNoCopy));
	}
	menu->SetItemImage(kUseWildcardCmd + offset, jx_filter_wildcard);
	menu->SetItemImage(kUseRegexCmd + offset, jx_filter_regex);
};

#endif
