// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_FileListDirector_Preferences
#define _H_FileListDirector_Preferences

static const JUtf8Byte* kPreferencesMenuStr =
"* %i __ToolbarButtons::FileListDirector"
"|* %i __FileTypes::FileListDirector"
"|* %i __ExternalEditors::FileListDirector"
"|* %i __FileManagerWebBrowser::FileListDirector"
"|* %i __Miscellaneous::FileListDirector %l"
"|* %i __SaveWindowSizeAsDefault::FileListDirector"
;

#include "FileListDirector-Preferences-enum.h"


static void ConfigurePreferencesMenu(JXTextMenu* menu, const int offset = 0) {
	if (offset == 0 && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts("#p");
	}
};

#endif
