// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_FileListDirector_Project_enum
#define _H_FileListDirector_Project_enum

enum {
	kShowSymbolBrowserCmd=1,
	kShowCTreeCmd,
	kShowDTreeCmd,
	kShowGoTreeCmd,
	kShowJavaTreeCmd,
	kShowPHPTreeCmd,
	kViewManPageCmd,
	kFindFileCmd,
	kSearchFilesCmd,
	kDiffFilesCmd,
	kSaveAllTextCmd,
	kCloseAllTextCmd,
};

#endif
