// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_FileListDirector_Project
#define _H_FileListDirector_Project

static const JUtf8Byte* kProjectMenuStr =
"* %i ShowSymbolBrowser::FileListDirector"
"|* %i ShowCPPClassTree::FileListDirector"
"|* %i ShowDClassTree::FileListDirector"
"|* %i ShowGoClassTree::FileListDirector"
"|* %i ShowJavaClassTree::FileListDirector"
"|* %i ShowPHPClassTree::FileListDirector"
"|* %i ViewManPage::FileListDirector %l"
"|* %i FindFile::FileListDirector"
"|* %i SearchFiles::FileListDirector"
"|* %i DiffFiles::FileListDirector %l"
"|* %i SaveAllTextFiles::FileListDirector"
"|* %i CloseAllTextFiles::FileListDirector"
;

enum {
	kShowSymbolBrowserCmd=1,
	kShowCTreeCmd,
	kShowDTreeCmd,
	kShowGoTreeCmd,
	kShowJavaTreeCmd,
	kShowPHPTreeCmd,
	kViewManPageCmd,
	kFindFileCmd,
	kSearchFilesCmd,
	kDiffFilesCmd,
	kSaveAllTextCmd,
	kCloseAllTextCmd,
};

#ifndef _H_jcc_show_symbol_list
#define _H_jcc_show_symbol_list
#include "jcc_show_symbol_list.xpm"
#endif
#ifndef _H_jcc_show_c_tree
#define _H_jcc_show_c_tree
#include "jcc_show_c_tree.xpm"
#endif
#ifndef _H_jcc_show_d_tree
#define _H_jcc_show_d_tree
#include "jcc_show_d_tree.xpm"
#endif
#ifndef _H_jcc_show_go_tree
#define _H_jcc_show_go_tree
#include "jcc_show_go_tree.xpm"
#endif
#ifndef _H_jcc_show_java_tree
#define _H_jcc_show_java_tree
#include "jcc_show_java_tree.xpm"
#endif
#ifndef _H_jcc_show_php_tree
#define _H_jcc_show_php_tree
#include "jcc_show_php_tree.xpm"
#endif
#ifndef _H_jcc_view_man_page
#define _H_jcc_view_man_page
#include "jcc_view_man_page.xpm"
#endif
#ifndef _H_jcc_search_files
#define _H_jcc_search_files
#include "jcc_search_files.xpm"
#endif
#ifndef _H_jx_af_image_jx_jx_file_save_all
#define _H_jx_af_image_jx_jx_file_save_all
#include <jx-af/image/jx/jx_file_save_all.xpm>
#endif

static void ConfigureProjectMenu(JXTextMenu* menu, const int offset = 0) {
	if (offset == 0 && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts(JString("#p", JString::kNoCopy));
	}
	menu->SetItemImage(kShowSymbolBrowserCmd + offset, jcc_show_symbol_list);
	menu->SetItemImage(kShowCTreeCmd + offset, jcc_show_c_tree);
	menu->SetItemImage(kShowDTreeCmd + offset, jcc_show_d_tree);
	menu->SetItemImage(kShowGoTreeCmd + offset, jcc_show_go_tree);
	menu->SetItemImage(kShowJavaTreeCmd + offset, jcc_show_java_tree);
	menu->SetItemImage(kShowPHPTreeCmd + offset, jcc_show_php_tree);
	menu->SetItemImage(kViewManPageCmd + offset, jcc_view_man_page);
	menu->SetItemImage(kSearchFilesCmd + offset, jcc_search_files);
	menu->SetItemImage(kSaveAllTextCmd + offset, jx_file_save_all);
};

#endif
