// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_GoTreeDirector_Tree
#define _H_GoTreeDirector_Tree

static const JUtf8Byte* kTreeMenuStr =
"* %i EditSearchPaths::GoTreeDirector"
"|* %i UpdateClassTree::GoTreeDirector"
"|* %i MinimizeMILinkLength::GoTreeDirector %l"
"|* %i OpenSelectedFiles::GoTreeDirector"
"|* %i OpenClassFnList::GoTreeDirector %l"
"|* %i CollapseClasses::GoTreeDirector"
"|* %i ExpandClasses::GoTreeDirector"
"|* %i ExpandAllClasses::GoTreeDirector %l"
"|* %i SelectParentClass::GoTreeDirector"
"|* %i SelectDescendantClass::GoTreeDirector"
"|* %i CopyClassName::GoTreeDirector %l"
"|* %i FindFunction::GoTreeDirector"
;

#include "GoTreeDirector-Tree-enum.h"

#ifndef _H_jx_af_image_jx_jx_edit_copy
#define _H_jx_af_image_jx_jx_edit_copy
#include <jx-af/image/jx/jx_edit_copy.xpm>
#endif

static void ConfigureTreeMenu(JXTextMenu* menu, const int offset = 0) {
	if (offset == 0 && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts("#t");
	}
	menu->SetItemImage(kCopySelNamesCmd + offset, jx_edit_copy);
};

#endif
