// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_ProjectDocument_Project
#define _H_ProjectDocument_Project

static const JUtf8Byte* kProjectMenuStr =
"* %i EditMakeConfig::ProjectDocument"
"|* %i UpdateMakefile::ProjectDocument %l"
"|* %i UpdateClassTree::ProjectDocument"
"|* %i ShowSymbolBrowser::ProjectDocument"
"|* %i ShowCPPClassTree::ProjectDocument"
"|* %i ShowDClassTree::ProjectDocument"
"|* %i ShowGoClassTree::ProjectDocument"
"|* %i ShowJavaClassTree::ProjectDocument"
"|* %i ShowPHPClassTree::ProjectDocument"
"|* %i ViewManPage::ProjectDocument %l"
"|* %i EditSearchPaths::ProjectDocument"
"|* %i ShowFileList::ProjectDocument"
"|* %i FindFile::ProjectDocument"
"|* %i SearchFiles::ProjectDocument"
"|* %i DiffFiles::ProjectDocument"
;

enum {
	kOpenMakeConfigDlogCmd=1,
	kUpdateMakefileCmd,
	kUpdateSymbolDBCmd,
	kShowSymbolBrowserCmd,
	kShowCTreeCmd,
	kShowDTreeCmd,
	kShowGoTreeCmd,
	kShowJavaTreeCmd,
	kShowPHPTreeCmd,
	kViewManPageCmd,
	kEditSearchPathsCmd,
	kShowFileListCmd,
	kFindFileCmd,
	kSearchFilesCmd,
	kDiffFilesCmd,
};


static void ConfigureProjectMenu(JXTextMenu* menu, const int offset = 0) {
	if (offset == 0 && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts(JString("#p", JString::kNoCopy));
	}
};

#endif
