// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_ProjectTable_Context_enum
#define _H_ProjectTable_Context_enum

enum {
	kOpenFilesCmd=1,
	kOpenComplFilesCmd,
	kEditSubprojConfigCmd,
	kNewGroupCmd,
	kAddFilesCmd,
	kAddDirTreeCmd,
	kRemoveSelCmd,
	kEditPathCmd,
	kDiffSmartCmd,
	kDiffVCSCmd,
	kShowLocationCmd,
};

#endif
