// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_ProjectDocument_File
#define _H_ProjectDocument_File

static const JUtf8Byte* kFileMenuStr =
"* %i NewTextFile::ProjectDocument"
"|* %i NewTextFileFromTmpl::ProjectDocument"
"|* %i NewProject::ProjectDocument %l"
"|* %i OpenSomething::ProjectDocument"
"|* %i __RecentProjects::ProjectDocument"
"|* %i __RecentTextFiles::ProjectDocument %l"
"|* %i SaveFile::ProjectDocument"
"|* %i SaveAsTemplate::ProjectDocument %l"
"|* %i PageSetup::JX"
"|* %i Print::JX %l"
"|* %i CloseWindow::JX"
"|* %i Quit::JX"
;

enum {
	kNewTextEditorCmd=1,
	kNewTextTemplateCmd,
	kNewProjectCmd,
	kOpenSomethingCmd,
	kRecentProjectMenuCmd,
	kRecentTextMenuCmd,
	kSaveCmd,
	kSaveAsTemplateCmd,
	kPageSetupCmd,
	kPrintCmd,
	kCloseCmd,
	kQuitCmd,
};

#ifndef _H_jx_af_image_jx_jx_file_new
#define _H_jx_af_image_jx_jx_file_new
#include <jx-af/image/jx/jx_file_new.xpm>
#endif
#ifndef _H_jx_af_image_jx_jx_file_open
#define _H_jx_af_image_jx_jx_file_open
#include <jx-af/image/jx/jx_file_open.xpm>
#endif
#ifndef _H_jx_af_image_jx_jx_file_save
#define _H_jx_af_image_jx_jx_file_save
#include <jx-af/image/jx/jx_file_save.xpm>
#endif
#ifndef _H_jx_af_image_jx_jx_file_print
#define _H_jx_af_image_jx_jx_file_print
#include <jx-af/image/jx/jx_file_print.xpm>
#endif

static void ConfigureFileMenu(JXTextMenu* menu, const int offset = 0) {
	if (offset == 0 && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts(JString("#f", JString::kNoCopy));
	}
	menu->SetItemImage(kNewTextEditorCmd + offset, jx_file_new);
	menu->SetItemImage(kOpenSomethingCmd + offset, jx_file_open);
	menu->SetItemImage(kSaveCmd + offset, jx_file_save);
	menu->SetItemImage(kPrintCmd + offset, jx_file_print);
};

#endif
