// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_ProjectDocument_File_enum
#define _H_ProjectDocument_File_enum

enum {
	kNewTextEditorCmd=1,
	kNewTextTemplateCmd,
	kNewProjectCmd,
	kOpenSomethingCmd,
	kRecentProjectMenuCmd,
	kRecentTextMenuCmd,
	kSaveCmd,
	kSaveAsTemplateCmd,
	kPageSetupCmd,
	kPrintCmd,
	kCloseCmd,
	kQuitCmd,
};

#endif
