// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_ProjectDocument_Project_enum
#define _H_ProjectDocument_Project_enum

enum {
	kOpenMakeConfigDlogCmd=1,
	kUpdateMakefileCmd,
	kUpdateSymbolDBCmd,
	kShowSymbolBrowserCmd,
	kShowCTreeCmd,
	kShowDTreeCmd,
	kShowGoTreeCmd,
	kShowJavaTreeCmd,
	kShowPHPTreeCmd,
	kViewManPageCmd,
	kEditSearchPathsCmd,
	kShowFileListCmd,
	kFindFileCmd,
	kSearchFilesCmd,
	kDiffFilesCmd,
};

#endif
