// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_ProjectDocument_Source_enum
#define _H_ProjectDocument_Source_enum

enum {
	kNewGroupCmd=1,
	kAddFilesCmd,
	kAddDirTreeCmd,
	kRemoveSelCmd,
	kOpenFilesCmd,
	kOpenComplFilesCmd,
	kEditPathCmd,
	kEditSubprojConfigCmd,
	kDiffSmartCmd,
	kDiffVCSCmd,
	kShowLocationCmd,
	kSaveAllTextCmd,
	kCloseAllTextCmd,
};

#endif
