// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_ProjectDocument_Preferences
#define _H_ProjectDocument_Preferences

static const JUtf8Byte* kPreferencesMenuStr =
"* %i __Project::ProjectDocument"
"|* %i __ToolbarButtons::ProjectDocument"
"|* %i __FileTypes::ProjectDocument"
"|* %i __ExternalEditors::ProjectDocument"
"|* %i __FileManagerWebBrowser::ProjectDocument"
"|* %i __Miscellaneous::ProjectDocument %l"
"|* %i __SaveWindowSizeAsDefault::ProjectDocument"
;

enum {
	kProjectPrefsCmd=1,
	kToolBarPrefsCmd,
	kEditFileTypesCmd,
	kChooseExtEditorsCmd,
	kShowLocationPrefsCmd,
	kMiscPrefsCmd,
	kSaveWindSizeCmd,
};


static void ConfigurePreferencesMenu(JXTextMenu* menu, const int offset = 0) {
	if (offset == 0 && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts(JString("#p", JString::kNoCopy));
	}
};

#endif
