// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_ProjectTable_Context
#define _H_ProjectTable_Context

static const JUtf8Byte* kContextMenuStr =
"* %i __OpenSelectedFiles::ProjectTable"
"|* %i __OpenComplementFiles::ProjectTable %l"
"|* %i __EditSubProjectConfiguration::ProjectTable %l"
"|* %i __NewGroup::ProjectTable"
"|* %i __AddFiles::ProjectTable"
"|* %i __AddDirectoryTree::ProjectTable"
"|* %i __RemoveSelectedItems::ProjectTable %l"
"|* %i __EditFilePath::ProjectTable %l"
"|* %i __CompareSelectedFilesWithBackup::ProjectTable"
"|* %i __CompareSelectedFilesWithVersionControl::ProjectTable"
"|* %i __ShowSelectedFilesInFileManager::ProjectTable"
;

#include "ProjectTable-Context-enum.h"


static void ConfigureContextMenu(JXTextMenu* menu, const int offset = 0) {
};

#endif
