// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_RunCommandDialog_SaveCmd
#define _H_RunCommandDialog_SaveCmd

static const JUtf8Byte* kSaveCmdMenuStr =
"* %i __ForAllProjects::RunCommandDialog"
"|* %i __ForActiveProject::RunCommandDialog"
;

enum {
	kSaveForAllCmd=1,
	kSaveForActiveCmd,
};


static void ConfigureSaveCmdMenu(JXTextMenu* menu, const int offset = 0) {
};

#endif
