// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_RunCommandDialog_SaveCmd_enum
#define _H_RunCommandDialog_SaveCmd_enum

enum {
	kSaveForAllCmd=1,
	kSaveForActiveCmd,
};

#endif
