// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_SaveNewProjectDialog_Template
#define _H_SaveNewProjectDialog_Template

static const JUtf8Byte* kTemplateMenuStr =
"* %r %i __None::SaveNewProjectDialog %l"
;

enum {
	kNoTemplateCmd=1,
};


static void ConfigureTemplateMenu(JXTextMenu* menu, const int offset = 0) {
};

#endif
