// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_SearchDocument_Match_enum
#define _H_SearchDocument_Match_enum

enum {
	kFirstMatchCmd=1,
	kPrevMatchCmd,
	kNextMatchCmd,
	kOpenFileCmd,
};

#endif
