// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_SearchTextDialog_FileList_enum
#define _H_SearchTextDialog_FileList_enum

enum {
	kShowMatchTextCmd=1,
	kListFilesWithoutMatchCmd,
	kAddFilesCmd,
	kRemoveSelCmd,
	kRemoveAllCmd,
	kLoadFileSetCmd,
	kSaveFileSetCmd,
};

#endif
