// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_SymbolDirector_Symbol
#define _H_SymbolDirector_Symbol

static const JUtf8Byte* kSymbolMenuStr =
"* %i EditSearchPaths::SymbolDirector"
"|* %i UpdateClassTree::SymbolDirector %l"
"|* %i OpenSelectedFiles::SymbolDirector"
"|* %i CopySymbolName::SymbolDirector %l"
"|* %i FindSelectionInProject::SymbolDirector"
"|* %i CloseAllSymSR::SymbolDirector"
;

enum {
	kEditSearchPathsCmd=1,
	kUpdateCurrentCmd,
	kOpenFileCmd,
	kCopySelNamesCmd,
	kFindSelectedSymbolCmd,
	kCloseAllSymSRCmd,
};

#ifndef _H_jx_af_image_jx_jx_file_open
#define _H_jx_af_image_jx_jx_file_open
#include <jx-af/image/jx/jx_file_open.xpm>
#endif
#ifndef _H_jx_af_image_jx_jx_edit_copy
#define _H_jx_af_image_jx_jx_edit_copy
#include <jx-af/image/jx/jx_edit_copy.xpm>
#endif

static void ConfigureSymbolMenu(JXTextMenu* menu, const int offset = 0) {
	if (offset == 0 && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts(JString("#s", JString::kNoCopy));
	}
	menu->SetItemImage(kOpenFileCmd + offset, jx_file_open);
	menu->SetItemImage(kCopySelNamesCmd + offset, jx_edit_copy);
};

#endif
