// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_SymbolSRDirector_Actions_enum
#define _H_SymbolSRDirector_Actions_enum

enum {
	kCopySelNamesCmd=1,
	kUpdateCmd,
	kShowCTreeCmd,
	kShowDTreeCmd,
	kShowGoTreeCmd,
	kShowJavaTreeCmd,
	kShowPHPTreeCmd,
	kCloseWindowCmd,
	kCloseAllCmd,
};

#endif
