// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_SymbolDirector_Preferences_enum
#define _H_SymbolDirector_Preferences_enum

enum {
	kSymbolPrefsCmd=1,
	kToolBarPrefsCmd,
	kEditFileTypesCmd,
	kChooseExtEditorsCmd,
	kShowLocationPrefsCmd,
	kMiscPrefsCmd,
	kSaveWindSizeCmd,
};

#endif
