// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_SymbolDirector_Symbol_enum
#define _H_SymbolDirector_Symbol_enum

enum {
	kEditSearchPathsCmd=1,
	kUpdateCurrentCmd,
	kOpenFileCmd,
	kCopySelNamesCmd,
	kFindSelectedSymbolCmd,
	kCloseAllSymSRCmd,
};

#endif
