// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_TEScriptMenu_Suffix
#define _H_TEScriptMenu_Suffix

static const JUtf8Byte* kSuffixMenuStr =
"* %i __NewScript::TEScriptMenu"
"|* %i __OpenDirectory::TEScriptMenu"
;

#include "TEScriptMenu-Suffix-enum.h"


static void ConfigureSuffixMenu(JXTextMenu* menu, const int offset = 0) {
};

#endif
