// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_TEScriptMenu_Suffix_enum
#define _H_TEScriptMenu_Suffix_enum

enum {
	kOpenDirectoryCmdOffset=1,
	kNewScriptCmdOffset,
};

#endif
