// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_TextEditor_Search
#define _H_TextEditor_Search

static const JUtf8Byte* kSearchMenuStr =
"* %i BalanceGroupingSymbol::TextEditor %l"
"|* %i GoToLine::TextEditor"
"|* %i GoToColumn::TextEditor"
"|* %i PlaceBookmark::TextEditor %l"
"|* %i OpenSelectionAsFile::TextEditor"
"|* %i FindFile::TextEditor %l"
"|* %i FindSelectionInProject::TextEditor"
"|* %i FindSelectionInProjectNoContext::TextEditor"
"|* %i FindSelectionInManPage::TextEditor"
"|* %i OpenManPage::TextEditor %l"
"|* %i OpenPrevListItem::TextEditor"
"|* %i OpenNextListItem::TextEditor"
;

enum {
	kBalanceCmd=1,
	kGoToLineCmd,
	kGoToColCmd,
	kPlaceBookmarkCmd,
	kOpenSelectionAsFileCmd,
	kFindSourceFileCmd,
	kFindSelectionAsSymbolCmd,
	kFindSelectionAsSymbolNoContextCmd,
	kFindSelectionInManPageCmd,
	kViewManPageCmd,
	kOpenPrevListItemCmd,
	kOpenNextListItemCmd,
};

#ifndef _H_jcc_balance_braces
#define _H_jcc_balance_braces
#include "jcc_balance_braces.xpm"
#endif
#ifndef _H_jcc_view_man_page
#define _H_jcc_view_man_page
#include "jcc_view_man_page.xpm"
#endif

static void ConfigureSearchMenu(JXTextMenu* menu, const int offset = 0) {
	menu->SetItemImage(kBalanceCmd + offset, jcc_balance_braces);
	menu->SetItemImage(kViewManPageCmd + offset, jcc_view_man_page);
};

#endif
