// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_TextDocument_Settings_enum
#define _H_TextDocument_Settings_enum

enum {
	kTabWidthCmd=1,
	kToggleAutoIndentCmd,
	kToggleTabInsertsSpacesCmd,
	kToggleWhitespaceCmd,
	kToggleWordWrapCmd,
	kToggleReadOnlyCmd,
};

#endif
