// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_TextDocument_Preferences
#define _H_TextDocument_Preferences

static const JUtf8Byte* kPreferencesMenuStr =
"* %i __Project::TextDocument"
"|* %i __ToolbarButtons::TextDocument"
"|* %i __ExternalEditors::TextDocument"
"|* %i __FileManagerWebBrowser::TextDocument"
"|* %i __Miscellaneous::TextDocument %l"
"|* %i __FileTypes::TextDocument"
"|* %i __SyntaxHighlighting::TextDocument"
"|* %i __Macros::TextDocument"
"|* %i __CleanParagraphMarginsRules::TextDocument %l"
"|* %i __SaveWindowSizeAsDefault::TextDocument"
;

enum {
	kEditorPrefsCmd=1,
	kToolBarPrefsCmd,
	kChooseExtEditorsCmd,
	kWWWPrefsCmd,
	kMiscPrefsCmd,
	kEditFileTypesCmd,
	kEditStylesSubmenuIndex,
	kEditMacrosCmd,
	kEditCRMRuleListsCmd,
	kSaveWindSizeCmd,
};


static void ConfigurePreferencesMenu(JXTextMenu* menu, const int offset = 0) {
	if (offset == 0 && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts(JString("#p", JString::kNoCopy));
	}
};

#endif
