// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_TextEditor_Context_enum
#define _H_TextEditor_Context_enum

enum {
	kContextCutCmd=1,
	kContextCopyCmd,
	kContextPasteCmd,
	kContextShiftLeftCmd,
	kContextShiftRightCmd,
	kContextCompleteCmd,
	kContextMacroCmd,
	kContextScriptSubmenuIndex,
	kContextFindSelBackCmd,
	kContextFindSelFwdCmd,
	kContextFindSymbolCmd,
	kContextFindSymbolNoContextCmd,
	kContextFindSymbolManPageCmd,
	kContextOpenSelAsFileCmd,
	kShowInFileMgrCmd,
	kContextBalanceCmd,
	kContextPlaceBookmarkCmd,
};

#endif
