// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_TextDocument_File_enum
#define _H_TextDocument_File_enum

enum {
	kNewTextEditorCmd=1,
	kNewTextTemplateCmd,
	kNewProjectCmd,
	kOpenSomethingCmd,
	kRecentProjectMenuCmd,
	kRecentTextMenuCmd,
	kSaveFileCmd,
	kSaveFileAsCmd,
	kSaveCopyAsCmd,
	kSaveAsTemplateCmd,
	kRevertCmd,
	kSaveAllFilesCmd,
	kFileFormatIndex,
	kDiffFilesCmd,
	kDiffSmartCmd,
	kDiffVCSCmd,
	kDiffMenuIndex,
	kShowInFileMgrCmd,
	kPTPageSetupCmd,
	kPrintPTCmd,
	kPSPageSetupCmd,
	kPrintPSCmd,
	kCloseCmd,
	kCloseAllCmd,
	kQuitCmd,
};

#endif
