// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_TextDocument_Diff_enum
#define _H_TextDocument_Diff_enum

enum {
	kDiffAs1Cmd=1,
	kDiffAs2Cmd,
	kDiffAsVCSCmd,
};

#endif
