// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_TextDocument_Diff
#define _H_TextDocument_Diff

static const JUtf8Byte* kDiffMenuStr =
"* %i __CompareAsFile1::TextDocument"
"|* %i __CompareAsFile2::TextDocument %l"
"|* %i __CompareWithVersionControl::TextDocument"
;

#include "TextDocument-Diff-enum.h"

#ifndef _H_jcc_compare_files_1
#define _H_jcc_compare_files_1
#include "jcc_compare_files_1.xpm"
#endif
#ifndef _H_jcc_compare_files_2
#define _H_jcc_compare_files_2
#include "jcc_compare_files_2.xpm"
#endif
#ifndef _H_jcc_compare_vcs_as
#define _H_jcc_compare_vcs_as
#include "jcc_compare_vcs_as.xpm"
#endif

static void ConfigureDiffMenu(JXTextMenu* menu, const int offset = 0) {
	menu->SetItemImage(kDiffAs1Cmd + offset, jcc_compare_files_1);
	menu->SetItemImage(kDiffAs2Cmd + offset, jcc_compare_files_2);
	menu->SetItemImage(kDiffAsVCSCmd + offset, jcc_compare_vcs_as);
};

#endif
