// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_TextDocument_Settings
#define _H_TextDocument_Settings

static const JUtf8Byte* kSettingsMenuStr =
"* %i __ChangeSpacesPerTab::TextDocument %l"
"|* %b %i __AutoIndent::TextDocument"
"|* %b %i __TabInsertsSpaces::TextDocument"
"|* %b %i __ShowWhitespace::TextDocument"
"|* %b %i __WordWrap::TextDocument"
"|* %b %i __ReadOnly::TextDocument"
;

#include "TextDocument-Settings-enum.h"

#ifndef _H_jcc_auto_indent
#define _H_jcc_auto_indent
#include "jcc_auto_indent.xpm"
#endif
#ifndef _H_jcc_tab_inserts_spaces
#define _H_jcc_tab_inserts_spaces
#include "jcc_tab_inserts_spaces.xpm"
#endif
#ifndef _H_jx_af_image_jx_jx_show_whitespace
#define _H_jx_af_image_jx_jx_show_whitespace
#include <jx-af/image/jx/jx_show_whitespace.xpm>
#endif
#ifndef _H_jcc_word_wrap
#define _H_jcc_word_wrap
#include "jcc_word_wrap.xpm"
#endif
#ifndef _H_jx_af_image_jx_jx_edit_read_only
#define _H_jx_af_image_jx_jx_edit_read_only
#include <jx-af/image/jx/jx_edit_read_only.xpm>
#endif

static void ConfigureSettingsMenu(JXTextMenu* menu, const int offset = 0) {
	menu->SetItemImage(kToggleAutoIndentCmd + offset, jcc_auto_indent);
	menu->SetItemImage(kToggleTabInsertsSpacesCmd + offset, jcc_tab_inserts_spaces);
	menu->SetItemImage(kToggleWhitespaceCmd + offset, jx_show_whitespace);
	menu->SetItemImage(kToggleWordWrapCmd + offset, jcc_word_wrap);
	menu->SetItemImage(kToggleReadOnlyCmd + offset, jx_edit_read_only);
};

#endif
