// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_TextDocument_PrefsStyles
#define _H_TextDocument_PrefsStyles

static const JUtf8Byte* kPrefsStylesMenuStr =
"* %i __BourneShell::TextDocument"
"|* %i __CShell::TextDocument"
"|* %i __CC::TextDocument"
"|* %i __C::TextDocument"
"|* %i __D::TextDocument"
"|* %i __Eiffel::TextDocument"
"|* %i __Go::TextDocument"
"|* %i __HTMLPHPJSPXML::TextDocument"
"|* %i __INI::TextDocument"
"|* %i __Java::TextDocument"
"|* %i __JavaProperties::TextDocument"
"|* %i __JavaScript::TextDocument"
"|* %i __Make::TextDocument"
"|* %i __Perl::TextDocument"
"|* %i __Python::TextDocument"
"|* %i __Ruby::TextDocument"
"|* %i __SQL::TextDocument"
"|* %i __TCL::TextDocument"
;

#include "TextDocument-PrefsStyles-enum.h"


static void ConfigurePrefsStylesMenu(JXTextMenu* menu, const int offset = 0) {
};

#endif
