// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_TextDocument_FileFormat_enum
#define _H_TextDocument_FileFormat_enum

enum {
	kUNIXFmtCmd=1,
	kMacFmtCmd,
	kDOSFmtCmd,
};

#endif
