// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_TextDocument_PrefsStyles_enum
#define _H_TextDocument_PrefsStyles_enum

enum {
	__BourneShell=1,
	__CShell,
	__C,
	__CSharp,
	__D,
	__Eiffel,
	__Go,
	__HTML,
	__INI,
	__Java,
	__Properties,
	__JavaScript,
	__Make,
	__Perl,
	__Python,
	__Ruby,
	__SQL,
	__TCL,
};

#endif
