// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_TreeDirector_Tree_enum
#define _H_TreeDirector_Tree_enum

enum {
	kEditSearchPathsCmd=1,
	kUpdateCurrentCmd,
	kForceMinMILinksCmd,
	kTreeOpenSourceCmd,
	kTreeOpenFnListCmd,
	kTreeCollapseCmd,
	kTreeExpandCmd,
	kTreeExpandAllCmd,
	kTreeSelParentsCmd,
	kTreeSelDescendantsCmd,
	kCopySelNamesCmd,
	kFindFnCmd,
};

#endif
