// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_TreeDirector_File_enum
#define _H_TreeDirector_File_enum

enum {
	kNewTextEditorCmd=1,
	kNewTextTemplateCmd,
	kNewProjectCmd,
	kOpenSomethingCmd,
	kRecentProjectMenuCmd,
	kRecentTextMenuCmd,
	kPSPageSetupCmd,
	kPrintPSCmd,
	kPrintEPSCmd,
	kCloseCmd,
	kQuitCmd,
};

#endif
