#!/bin/bash

# With no arguments, this script must install from an unpacked tgz.

PRE=$1;
if [[ -z $PRE ]]; then
	if [[ `uname -o` == Darwin ]]; then
		PRE=`brew --prefix`;
	else
		PRE=/usr/local;
	fi;
fi

BIN=$PRE/bin;
DOC=$PRE/share/doc/code-medic;
APP=$PRE/share/applications;
ICON=$PRE/share/pixmaps;

mkdir -p $BIN;
install -m755 medic $BIN;

ln -sf medic $BIN/code-medic;

mkdir -p $DOC;
cp README.md COPYING menu_strings $DOC;

if [[ -d desktop ]]; then
	mkdir -p $APP $ICON;
	cp desktop/code-medic.desktop $APP/;
	cp desktop/code-medic.png     $ICON/;
fi
