#!/bin/bash

# With no arguments, this script must install from an unpacked tgz.

PRE=$1

BIN=$PRE/usr/bin
DOC=$PRE/usr/share/doc/code_medic
APP=$PRE/usr/share/applications
ICON=$PRE/usr/share/pixmaps

if [[ ! -z $PRE ]]; then
	mkdir -p $BIN $APP $ICON;
fi

# medic

install -m755 medic $BIN

ln -sf jcc $BIN/code_medic

mkdir -p $DOC
cp README.md COPYING menu_strings $DOC

cp desktop/code_medic.desktop $APP/
cp desktop/code_medic.xpm     $ICON/
