#!/bin/bash

# With no arguments, this script must install from an unpacked tgz.

PRE=$1;

BIN=$PRE/usr/bin;
DOC=$PRE/usr/share/doc/code-medic;
APP=$PRE/usr/share/applications;
ICON=$PRE/usr/share/pixmaps;

mkdir -p $BIN;
install -m755 medic $BIN;

ln -sf medic $BIN/code-medic;

mkdir -p $DOC;
cp README.md COPYING menu_strings $DOC;

if [[ -d desktop ]]; then
	mkdir -p $APP $ICON;
	cp desktop/code_medic.desktop $APP/;
	cp desktop/code_medic.xpm     $ICON/;
fi
