#!/bin/bash

PRE=$1;

BIN=$PRE/usr/bin;
DOC=$PRE/usr/share/doc/code-medic;
APP=$PRE/usr/share/applications;
ICON=$PRE/usr/share/pixmaps;

rm -f  $BIN/medic $BIN/code-medic;
rm -rf $DOC;
rm -f  `find $APP -name 'code_medic*.desktop'`;
rm -f  `find $ICON -name 'code_medic*.xpm'`;
