name: jx-ide
title: JX IDE
base: core20
version: "7.1.5"
license: LGPL-2.1-or-later
source-code: https://github.com/jafl/jx-ide
issues: https://github.com/jafl/jx-ide/issues
contact: https://johnlindal.wixsite.com/aboutme/contact-me
summary: JX IDE is a graphical development environment for UNIX.
description: |
  Code Crusader provides project management, editing, and compiling.
  Its companion, Code Medic, provides debugging.
  Code Mill helps create derived C++ classes.
  System G provides an interface to the file system and git.
  Subversion Client provides a simple, graphical Subversion client.

grade: stable
confinement: classic

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: ppc64el

apps:
  code-crusader:
    command: bin/code-crusader
  code-medic:
    command: bin/code-medic
  code-mill:
    command: bin/code-mill
  systemg:
    command: bin/systemg
  svn-client:
    command: bin/svn-client

parts:
  jx-ide:
    plugin: autotools
    source: .
    override-pull: |
      snapcraftctl pull
      git clone https://github.com/jafl/system-g.git
      git clone https://github.com/jafl/subversion_client.git
      sudo locale-gen en_US.UTF-8
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
    build-environment:
      - JX_ROOT: /snap/jx-application-framework/current
      - PATH: $PATH:$JX_ROOT/bin
      - LD_LIBRARY_PATH: $SNAPCRAFT_PART_INSTALL/lib:$SNAPCRAFT_PART_INSTALL/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAPCRAFT_PART_INSTALL/usr/lib:$SNAPCRAFT_PART_INSTALL/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
      - SNAPCRAFT_PARALLEL_BUILD_COUNT: "1"
    autotools-configure-parameters:
      - release
    organize:
      bin/jcc: bin/code-crusader
      bin/medic: bin/code-medic
      bin/nps-svn-client: bin/svn-client
    stage:
      - bin/code-crusader
      - bin/code-medic
      - bin/code-mill
      - share/jxcb
      - bin/systemg
      - bin/svn-client
    build-packages:
      - g++-10
      - make
      - pkg-config
      - libeditorconfig-dev
      - liblldb-11-dev
      - libx11-dev
      - libxinerama-dev
      - libxft-dev
      - libxmu-dev
      - libxi-dev
      - libx11-xcb-dev
      - libxcb-xfixes0-dev
      - libxcb-dri2-0-dev
      - libxpm-dev
      - libjpeg-dev
      - libpng-dev
      - libgd-dev
      - libace-dev
      - libicu-dev
      - libpcre3-dev
      - libxml2-dev
      - libboost-fiber-dev
      - xutils-dev
      - libdrm-dev
      - aspell
      - locales
    build-snaps:
      - jx-application-framework
    after: [ libs ]
  libs:
    plugin: nil
    stage-packages:
      - libeditorconfig0
      - liblldb-11
      - libace-6.4.5
      - libfontconfig1
      - libfreetype6
      - libgd3
      - libicu66
      - libjbig0
      - libjpeg-turbo8
      - libpng16-16
      - libtiff5
      - libwebp6
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
      - libxext6
      - libxft2
      - libxinerama1
      - libxml2
      - libboost-fiber-dev
      - libxpm4
      - libxrender1
      - git
      - gitk
      - git-gui
      - xterm
      - openssh-client
      - subversion
