name: CI
on:
  push:
    branches: [ main ]
    tags: [ v* ]
  workflow_dispatch:
jobs:
  build-ubuntu:
    name: Build & Package Ubuntu
    runs-on: ubuntu-latest
    env:
      SONAR_SCANNER_VERSION: 4.4.0.2170
      SONAR_SERVER_URL: "https://sonarcloud.io"
      BUILD_WRAPPER_OUT_DIR: sonar_output
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set environment variables
        run: |
          echo SONAR_CACHE_PATH=$HOME/sonar_output >> $GITHUB_ENV
          echo FORCE_CACHE_UPDATE=${RANDOM}${RANDOM} >> $GITHUB_ENV

      - name: Sonar data cache
        id: cache-sonar-data
        uses: actions/cache@v2
        with:
          path: ${{ env.SONAR_CACHE_PATH }}
          key: ${{ runner.os }}-sonar-cache-${{ env.FORCE_CACHE_UPDATE }}
          restore-keys: |
            ${{ runner.os }}-sonar-cache-

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Download and set up sonar-scanner
        env:
          SONAR_SCANNER_DOWNLOAD_URL: https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${{ env.SONAR_SCANNER_VERSION }}-linux.zip
        run: |
          mkdir -p $HOME/.sonar
          curl -sSLo $HOME/.sonar/sonar-scanner.zip ${{ env.SONAR_SCANNER_DOWNLOAD_URL }}
          unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
          echo "$HOME/.sonar/sonar-scanner-${{ env.SONAR_SCANNER_VERSION }}-linux/bin" >> $GITHUB_PATH

      - name: Download and set up build-wrapper
        env:
          BUILD_WRAPPER_DOWNLOAD_URL: ${{ env.SONAR_SERVER_URL }}/static/cpp/build-wrapper-linux-x86.zip
        run: |
          curl -sSLo $HOME/.sonar/build-wrapper-linux-x86.zip ${{ env.BUILD_WRAPPER_DOWNLOAD_URL }}
          unzip -o $HOME/.sonar/build-wrapper-linux-x86.zip -d $HOME/.sonar/
          echo "$HOME/.sonar/build-wrapper-linux-x86" >> $GITHUB_PATH

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: cpp

      - name: Configure
        run: |
          curl -O http://libjx.sourceforge.net/ci/re-flex.deb
          sudo apt install ./re-flex.deb
          curl -O http://libjx.sourceforge.net/ci/jx-application-framework.deb
          sudo apt install ./jx-application-framework.deb
          ./configure ci
          make Makefiles

      - name: Build
        run: |
          touch code_medic/backend/gdb/GDBVarTreeParserY.cpp code_medic/backend/gdb/GDBVarTreeParserY.hpp
          build-wrapper-linux-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} make all

      - name: Run tests
        continue-on-error: true
        run: |
          make test
          cd code_crusader/test
          make reset

      - name: Run sonar-scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: sonar-scanner --define sonar.host.url="${{ env.SONAR_SERVER_URL }}" --define sonar.cfamily.build-wrapper-output="${{ env.BUILD_WRAPPER_OUT_DIR }}"

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v1

      - name: Build release packages
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          make release
          mv ../code_*_* .

      - name: Save release packages
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: code_*_*

  build-macos:
    name: Build & Package MacOS
    runs-on: macos-11
    env:
      PKG_CONFIG_PATH: /usr/local/opt/icu4c/lib/pkgconfig
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure
        run: |
          curl -O http://libjx.sourceforge.net/ci/jx-application-framework_darwin.tgz
          tar -xzf jx-application-framework_darwin.tgz
          pushd jx-application-framework-1ci
          ./install /usr/local
          popd
          ./configure ci
          brew install cask
          brew install --cask xquartz
          make Makefiles

      - name: Build
        run: make all

      - name: Build release packages
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          export PATH=/usr/local/opt/coreutils/libexec/gnubin:$PATH
          make release
          mv ../code_*_* .

      - name: Save release packages
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: code_*_*

  release:
    name: Upload releases
    runs-on: ubuntu-latest
    needs: [ build-ubuntu, build-macos ]
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: release

      - name: Save release packages
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: code_*_*
          tag: ${{ github.ref }}
          file_glob: true
